// scripts/generate-photolog.ts
//
// Reads the blur/ folder, counts photos per year, and writes:
//   - src/photolog-utils.ts   (metadata: counts per year)
//   - src/photolog.ts         (flat photo array with blur data URIs)
//
// Years and counts are auto-discovered. Do not edit those files by hand.

import fs from "fs";
import path, { dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, "..");

const BLUR_ROOT = path.resolve(REPO_ROOT, "public/photolog/blur");
const UTILS_FILE = path.resolve(REPO_ROOT, "src/photolog-utils.ts");
const OUTPUT_FILE = path.resolve(REPO_ROOT, "src/photolog.ts");

// ---------- discover years from blur/ ----------

if (!fs.existsSync(BLUR_ROOT)) {
  console.error(`error: ${BLUR_ROOT} does not exist. Run blur.sh first.`);
  process.exit(1);
}

const years = fs
  .readdirSync(BLUR_ROOT)
  .filter((name) => /^\d{4}$/.test(name))
  .sort()
  .reverse(); // newest first

if (years.length === 0) {
  console.error("error: no year folders found in blur/");
  process.exit(1);
}

// ---------- count photos per year ----------

const counts: Record<string, number> = {};
for (const year of years) {
  const yearDir = path.join(BLUR_ROOT, year);
  const files = fs
    .readdirSync(yearDir)
    .filter((f) => /^\d+\.jpeg$/.test(f));
  counts[year] = files.length;
}

console.log("discovered counts:");
for (const [year, count] of Object.entries(counts)) {
  console.log(`  ${year}: ${count}`);
}

// ---------- write src/photolog-utils.ts ----------

const metadataLines = Object.entries(counts)
  .sort(([a], [b]) => b.localeCompare(a))
  .map(([year, count]) => `  "${year}": { count: ${count} },`)
  .join("\n");

const utilsContent = `// AUTO-GENERATED by scripts/generate-photolog.ts
// Do not edit by hand. Run \`npm run photos\` to regenerate.

export interface PhotoLogImage {
  blur: string;
  sq: string;
  hq: string;
}

export const PhotoLogMetadata: Record<string, { count: number }> = {
${metadataLines}
};
`;

fs.writeFileSync(UTILS_FILE, utilsContent, { flag: "w" });
console.log(`wrote ${path.relative(REPO_ROOT, UTILS_FILE).replace(/\\/g, "/")}`);

// ---------- build photos array ----------

function generateImageSrcForYear(year: string): PhotoLogImage[] {
  const count = counts[year];
  return Array.from({ length: count }, (_, i) => {
    const n = i + 1;
    const sq = `/photolog/sq/${year}/${n}.jpeg`;
    const hq = `/photolog/hq/${year}/${n}.jpeg`;
    const blurPath = path.join(BLUR_ROOT, year, `${n}.jpeg`);
    const blurBase64 = fs.readFileSync(blurPath, { encoding: "base64" });
    const blur = `data:image/jpeg;base64,${blurBase64}`;
    return { blur, sq, hq };
  }).reverse();
}

interface PhotoLogImage {
  blur: string;
  sq: string;
  hq: string;
}

const photos: PhotoLogImage[] = years.flatMap((year) =>
  generateImageSrcForYear(year),
);

fs.writeFileSync(
  OUTPUT_FILE,
  `// AUTO-GENERATED by scripts/generate-photolog.ts
// Do not edit by hand. Run \`npm run photos\` to regenerate.

export const photos = ${JSON.stringify(photos)};
`,
  { flag: "w" },
);

console.log(`wrote ${path.relative(REPO_ROOT, OUTPUT_FILE).replace(/\\/g, "/")}`);
console.log(`total: ${photos.length} photos across ${years.length} years`);