// AUTO-GENERATED by scripts/generate-photolog.ts
// Do not edit by hand. Run `npm run photos` to regenerate.

export interface PhotoLogImage {
  blur: string;
  sq: string;
  hq: string;
}

export const PhotoLogMetadata: Record<string, { count: number }> = {
  "2026": { count: 11 },
  "2025": { count: 16 },
  "2024": { count: 22 },
  "2023": { count: 2 },
  "2022": { count: 10 },
};
